<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 6.0.2 (Python 3.11.1 on win32)" generated="20230127 11:04:36.893" rpa="false" schemaversion="3">
<suite id="s1" name="Demo2" source="C:\Users\40032117\robot_project\api_suite\demo2.robot">
<test id="s1-t1" name="TC3" line="17">
<kw name="Create Session" library="RequestsLibrary">
<arg>alias=petshop</arg>
<arg>url=https://petstore.swagger.io/v2</arg>
<doc>Create Session: create a HTTP session to a server</doc>
<msg timestamp="20230127 11:04:37.116" level="INFO">Creating Session using : alias=petshop, url=https://petstore.swagger.io/v2, headers={},                     cookies={}, auth=None, timeout=None, proxies=None, verify=False,                     debug=0 </msg>
<status status="PASS" starttime="20230127 11:04:37.116" endtime="20230127 11:04:37.132"/>
</kw>
<kw name="GET On Session" library="RequestsLibrary">
<var>${response}</var>
<arg>alias=petshop</arg>
<arg>url=pet/findByStatus?status=sold</arg>
<doc>Sends a GET request on a previously created HTTP Session.</doc>
<msg timestamp="20230127 11:04:37.132" level="WARN">Retrying (RetryAdapter(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPSConnection object at 0x000001AA11849910&gt;: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /v2/pet/findByStatus?status=sold</msg>
<msg timestamp="20230127 11:04:37.346" level="WARN">Retrying (RetryAdapter(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPSConnection object at 0x000001AA11857790&gt;: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /v2/pet/findByStatus?status=sold</msg>
<msg timestamp="20230127 11:04:37.747" level="WARN">Retrying (RetryAdapter(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPSConnection object at 0x000001AA1186C150&gt;: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /v2/pet/findByStatus?status=sold</msg>
<msg timestamp="20230127 11:04:37.747" level="FAIL">ConnectionError: HTTPSConnectionPool(host='petstore.swagger.io', port=443): Max retries exceeded with url: /v2/pet/findByStatus?status=sold (Caused by NewConnectionError('&lt;urllib3.connection.HTTPSConnection object at 0x000001AA1186CF50&gt;: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))</msg>
<status status="FAIL" starttime="20230127 11:04:37.132" endtime="20230127 11:04:37.756"/>
</kw>
<kw name="Status Should Be" library="RequestsLibrary">
<arg>200</arg>
<doc>Fails if response status code is different than the expected.</doc>
<status status="NOT RUN" starttime="20230127 11:04:37.756" endtime="20230127 11:04:37.756"/>
</kw>
<kw name="Log" library="BuiltIn">
<arg>${response.json()}</arg>
<doc>Logs the given message with the given level.</doc>
<status status="NOT RUN" starttime="20230127 11:04:37.756" endtime="20230127 11:04:37.756"/>
</kw>
<kw name="Log" library="BuiltIn">
<arg>${response.json()}[0][id]</arg>
<doc>Logs the given message with the given level.</doc>
<status status="NOT RUN" starttime="20230127 11:04:37.756" endtime="20230127 11:04:37.756"/>
</kw>
<status status="FAIL" starttime="20230127 11:04:37.116" endtime="20230127 11:04:37.756">ConnectionError: HTTPSConnectionPool(host='petstore.swagger.io', port=443): Max retries exceeded with url: /v2/pet/findByStatus?status=sold (Caused by NewConnectionError('&lt;urllib3.connection.HTTPSConnection object at 0x000001AA1186CF50&gt;: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))</status>
</test>
<status status="FAIL" starttime="20230127 11:04:36.899" endtime="20230127 11:04:37.756"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" skip="0" id="s1" name="Demo2">Demo2</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20230127 11:04:37.132" level="WARN">Retrying (RetryAdapter(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPSConnection object at 0x000001AA11849910&gt;: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /v2/pet/findByStatus?status=sold</msg>
<msg timestamp="20230127 11:04:37.346" level="WARN">Retrying (RetryAdapter(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPSConnection object at 0x000001AA11857790&gt;: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /v2/pet/findByStatus?status=sold</msg>
<msg timestamp="20230127 11:04:37.747" level="WARN">Retrying (RetryAdapter(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPSConnection object at 0x000001AA1186C150&gt;: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /v2/pet/findByStatus?status=sold</msg>
</errors>
</robot>
